server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/main_service_db
    username: springuser
    password: spring123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
